### PR TITLE
Status feature current branch

### PR DESCRIPTION
**Pull request by cathyAkoth**

### CODE REVIEW

**Comment by okellodaniel** [comment]
I have failed to merge, like I am restricted from resolving

**Review by okellodaniel — COMMENTED** [review]
Nice Work Cathy

**Comment by cathyAkoth** [comment]
I have also failed to merge. but the development branch has all the code
from uploadand download branch

**Comment by cathyAkoth** [comment]
lets get some time tomorrow and look at this.

**Comment by okellodaniel** [comment]
Is it Okay with you if I resolve these conflicts?

**Comment by okellodaniel** [comment]
Oh okay, lets meet and resolve them conflicts

**Comment by cathyAkoth** [comment]
if you so wish but I already did. you can check with the deployed app using
swagger. Status is working. you dont have to merge the branches

**Comment by okellodaniel** [comment]
Well, then you can close this  PR

**Pull request closed without merging**
